
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
                
- name: mart_regional_performance
    description: "Final reporting table showing Sales and Profit aggregated by Region and Category."
    columns:
      - name: region
        description: "Geographic region of the superstore."
      - name: total_profit
        description: "The sum of all profit for this region/category."